/**
 * Schema for project analysis file generated by Cursor (run the analysis prompt in the repo).
 * Import flow creates Design(s), Architecture(s), Features, Tickets, PromptRecords and links them to the project.
 */

import type { ArchitectureCategory } from "./architecture";
import type { DesignConfig } from "./design";

/** Single architecture entry in analysis (no id/timestamps). */
export interface AnalysisArchitecture {
  name: string;
  category: ArchitectureCategory | string;
  description: string;
  practices: string;
  scenarios: string;
  references?: string;
  anti_patterns?: string;
  examples?: string;
}

/** Single design entry in analysis (no id/timestamps). */
export interface AnalysisDesign {
  name: string;
  config: DesignConfig;
}

/** Ticket suggestion within a feature. */
export interface AnalysisTicket {
  title: string;
  description?: string;
}

/** PromptRecord suggestion within a feature. */
export interface AnalysisPromptRecord {
  title: string;
  content: string;
}

/** Error or risk from analysis. */
export interface AnalysisError {
  severity: string;
  message: string;
  location?: string;
}

/** Root analysis file shape. Output only valid JSON matching this (no markdown fence). */
export interface ProjectAnalysisSchema {
  /** Short summary of the app's current state. */
  currentState?: string;
  /** One or more architecture definitions. */
  architecture?: AnalysisArchitecture | AnalysisArchitecture[];
  /** One or more design definitions. */
  design?: AnalysisDesign | AnalysisDesign[];
  /** Errors, risks, anti-patterns. */
  errors?: AnalysisError[];
}

/** Normalize architecture to array. */
export function analysisArchitectures(
  a: ProjectAnalysisSchema["architecture"]
): AnalysisArchitecture[] {
  if (a == null) return [];
  return Array.isArray(a) ? a : [a];
}

/** Normalize design to array. */
export function analysisDesigns(d: ProjectAnalysisSchema["design"]): AnalysisDesign[] {
  if (d == null) return [];
  return Array.isArray(d) ? d : [d];
}


